# Generated by Django 5.0.6 on 2024-07-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='positions',
            field=models.CharField(choices=[('NS', 'Новость'), ('AR', 'Статья')], default='NS', max_length=2),
        ),
    ]
